#!/bin/bash
# vim: set ft=sh

set -e

<% conn = link('mongodb_config_agent') %>

<% if conn.p("mongo_ops.backup_enabled") %>

export PATH=/var/vcap/packages/jq/bin:$PATH

  clusters=($(curl --fail --digest  -u "<%= conn.p('mongo_ops.username') %>:<%= conn.p('mongo_ops.api_key') %>" <%= conn.p('mongo_ops.url') %>/api/public/v1.0/groups/<%= conn.p('mongo_ops.group_id') %>/clusters | jq -r ".results[].id"))
  for cluster in "${clusters[@]}"
  do
    curl -H "Content-Type: application/json" -X PATCH --fail --digest  -u "<%= conn.p('mongo_ops.username') %>:<%= conn.p('mongo_ops.api_key') %>" <%= conn.p('mongo_ops.url') %>/api/public/v1.0/groups/<%= conn.p('mongo_ops.group_id') %>/backupConfigs/${cluster} -d '{"statusName": "STOPPED"}'

    curl -H "Content-Type: application/json" -X PATCH --fail --digest  -u "<%= conn.p('mongo_ops.username') %>:<%= conn.p('mongo_ops.api_key') %>" <%= conn.p('mongo_ops.url') %>/api/public/v1.0/groups/<%= conn.p('mongo_ops.group_id') %>/backupConfigs/${cluster} -d '{"statusName": "TERMINATING"}'
  done
<% end %>

curl --fail -u "<%= conn.p('mongo_ops.username') %>:<%= conn.p('mongo_ops.api_key') %>" \
  -X DELETE --digest \
  -i "<%= conn.p('mongo_ops.url') %>/api/public/v1.0/groups/<%= conn.p('mongo_ops.group_id') %>"
