#!/bin/bash
# vim: set ft=sh

set -e

<% conn = link('mongodb_config_agent') %>

<% if conn.p("mongo_ops.backup_enabled") %>

export PATH=/var/vcap/packages/jq/bin:$PATH

source /var/vcap/packages/mongodb-config-agent/mongo_utils.sh
export MONGO_OM_URL='<%= conn.p('mongo_ops.url') %>'
export MONGO_OM_USER='<%= conn.p('mongo_ops.username') %>'
export MONGO_OM_API_KEY='<%= conn.p('mongo_ops.api_key') %>'
export MONGO_OM_GROUP_ID='<%= conn.p('mongo_ops.group_id') %>'

  clusters=($(om_api_call "GET" "clusters" | jq -r ".results[].id"))
  for cluster in "${clusters[@]}"
  do
      om_api_call "PATCH" "backupConfigs/${cluster}" '{"statusName": "STOPPED"}'
      om_api_call "PATCH" "backupConfigs/${cluster}" '{"statusName": "TERMINATING"}'
      while true
      do
	stat=$(om_api_call "GET" "backupConfigs/${cluster}" | jq -r ".statusName")
	if [ $stat == "INACTIVE" ]; then
	    break
	else
	    sleep 5
	fi
      done
  done


<% end %>

om_api_call "DELETE" "" 
