#!/usr/bin/dumb-init /bin/bash

set -e

root_dir=$(pwd)

VERSION=$(cat version/number)

pushd git
  mkdir -p src/golang src/libsnmp src/cf-cli
  wget 'https://s3-us-west-1.amazonaws.com/cf-cli-releases/releases/v6.28.0/cf-cli_6.28.0_linux_x86-64.tgz' -O src/cf-cli/cf-cli_6.28.0_linux_x86-64.tgz --tries=7
  wget 'https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz' -O src/golang/go1.8.3.linux-amd64.tar.gz --tries=7
  wget 'http://security.ubuntu.com/ubuntu/pool/main/n/net-snmp/libsnmp30_5.7.2~dfsg-8.1ubuntu3.1_amd64.deb' -P src/libsnmp/ --tries=7
  wget 'http://security.ubuntu.com/ubuntu/pool/main/n/net-snmp/libsnmp-base_5.7.2~dfsg-8.1ubuntu3.1_all.deb' -P src/libsnmp/ --tries=7
  wget 'http://security.ubuntu.com/ubuntu/pool/main/p/perl/libperl5.18_5.18.2-2ubuntu1.1_amd64.deb' -P src/libsnmp/ --tries=7
  bosh create release --with-tarball --name mongodb --version ${VERSION}
  cp dev_releases/mongodb/mongodb-*.tgz $root_dir/git/tile/resources
popd

pushd odb
  cp on-demand-service-broker-*.tgz $root_dir/git/tile/resources
popd

pushd git/tile
  PREVIOUS_VERSION=$(cat tile.yml|grep resources/mongodb|grep -o -P "\\s*[v=]*\\s*([0-9]+)\\.([0-9]+)\\.([0-9]+)")
  sed -i "s/${PREVIOUS_VERSION}/${VERSION}/g" tile.yml
  tile build ${VERSION}
  cp product/mongodb-on-demand-*.pivotal $root_dir/tile
popd
