#!/usr/bin/dumb-init /bin/bash

set -e

root_dir=$(pwd)

mkdir -p /go/src/github.com/cf-platform-eng/mongodb-on-demand-release
cp -R git/* /go/src/github.com/cf-platform-eng/mongodb-on-demand-release

pushd /go/src/github.com/cf-platform-eng/mongodb-on-demand-release/src/mongodb-config-agent
  go test -v $(go list ./... | grep -v vendor)
popd

pushd /go/src/github.com/cf-platform-eng/mongodb-on-demand-release/src/mongodb-service-adapter
  go test -v $(go list ./... | grep -v vendor)
popd
