#!/usr/bin/dumb-init /bin/bash

set -e

root_dir=$(pwd)

cat > config.json << EOF
{
  "service_name": "$SERVICE_NAME",
  "plan_names": [
    "standalone"
  ],
  "retry": {
    "max_attempts": 10,
    "backoff": "linear",
    "baseline_interval_milliseconds": 1000
  },
  "apps_domain": "$CF_APPS_DOMAIN",
  "system_domain": "$CF_SYSTEM_DOMAIN",
  "api": "$CF_API",
  "admin_user": "$CF_USER",
  "admin_password": "$CF_PASSWORD",
  "space_name": "mongodb-on-demand-test-space",
  "org_name": "mongodb-on-demand-test-org",
  "skip_ssl_validation": true,
  "create_permissive_security_group": false
}
EOF

export CONFIG_PATH=$(pwd)/config.json

export PACKAGE_NAME=github.com/cf-platform-eng/mongodb-on-demand-release
export PACKAGE_DIR=$GOPATH/src/$PACKAGE_NAME
mkdir -p $PACKAGE_DIR
cp -a git/* $PACKAGE_DIR

pushd $PACKAGE_DIR/src/smoke-tests
  ./bin/test
popd
